name: 'Publish to NPM registry'
description: 'Publish package to NPM registry'
inputs:
  node-version:  # "20.x" or "22.x" or "24.x" or ".nvmrc" or "package.json"
    description: 'Version of Node.js (e.g. "20.x", "22.x", "24.x"), or version file name such like ".nvmrc" or "package.json". If omitted, automatically detects .nvmrc, .node-version, or package.json.'
    required: false
    default: ''
  fetch-depth:
    description: 'Fetch depth for git history'
    required: false
    default: '1'
  npm-publish-token:
    description: 'Token for publishing to NPM registry'
    required: true
  publish-command:
    description: 'Command to publish package'
    required: false
    default: 'npm publish'
  publish-flags:
    description: 'Additional flags for publish command (e.g. --access public, --provenance, --tag next)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Prepare
      uses: handy-common-utils/automation/github/actions/prepare-node@main
      with:
        node-version: ${{ inputs.node-version }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Publish
      run: |
        if [ ! -f .npmrc ]; then
          echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
        elif ! grep -q "_authToken" .npmrc; then
          echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
        fi
        if [ -n "${{ inputs.publish-flags }}" ]; then
          ${{ inputs.publish-command }} ${{ inputs.publish-flags }}
        else
          ${{ inputs.publish-command }}
        fi
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-publish-token }}
        NPM_PUBLISH_TOKEN: ${{ inputs.npm-publish-token }}
        NPM_TOKEN: ${{ inputs.npm-publish-token }}
