name: 'Publish to NPM registry'
inputs:
  node-version:  # "16.1" or "16.x" or "volta"
    description: 'Version of Node.js, or "volta"'
    required: false
    default: 'volta'
  npm-publish-token:
    description: 'Token for publishing to NPM registry'
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare
      uses: handy-common-utils/automation/github/actions/prepare-node@main
      with:
        node-version: ${{ inputs.node-version }}
    - name: Publish
      run: npm publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-publish-token }}