name: 'Publish to NPM registry'
description: 'Publish to NPM registry'
inputs:
  node-version:  # "16.1" or "16.x" or "package.json" or ".nvmrc"
    description: 'Version of Node.js, or version file name such like "package.json" or ".nvmrc"'
    required: false
    default: 'package.json'
  npm-publish-token:
    description: 'Token for publishing to NPM registry'
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare
      uses: handy-common-utils/automation/github/actions/prepare-node@main
      with:
        node-version: ${{ inputs.node-version }}
    - name: Publish
      run: |
        if [ ! -f .npmrc ]; then
          echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
        fi
        npm publish
      shell: bash
      env:
        NPM_PUBLISH_TOKEN: ${{ inputs.npm-publish-token }}
        NPM_TOKEN: ${{ inputs.npm-publish-token }}