name: 'Prepare (node)'
description: 'Prepare Node.js environment. It includes checking out code and running "npm ci". Caching of dependencies is covered too.'
inputs:
  node-version:  # "16.1" or "16.x" or "package.json" or ".nvmrc"
    description: 'Version of Node.js, or version file name such like "package.json" or ".nvmrc"'
    required: false
    default: 'package.json'
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Use Node.js (${{ inputs.node-version }})
      uses: actions/setup-node@v4
      with:
        node-version: ${{ (!startsWith(inputs.node-version, '.') && !endsWith(inputs.node-version, '.json') && inputs.node-version) || null }}
        node-version-file: ${{ ((startsWith(inputs.node-version, '.') || endsWith(inputs.node-version, '.json')) && inputs.node-version) || null }}
        cache: 'npm'
        cache-dependency-path: |
          package.json
          package-lock.json
    - name: Install dependencies
      run: npm ci
      shell: bash
