name: 'CI (node)'
inputs:
  node-version:  # "16.1" or "16.x" or "package.json"
    description: 'Version of Node.js, or version file name such like "package.json"'
    required: false
    default: 'package.json'
runs:
  using: "composite"
  steps:
    - name: Prepare
      uses: handy-common-utils/automation/github/actions/prepare-node@main
      with:
        node-version: ${{ inputs.node-version }}
    - name: Test
      run: npm test
      shell: bash
    - name: Upload test coverage report
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        flags: unittests # optional
        name: Result with Node version ${{ inputs.node-version }}
